spring:
  datasource:
    url: jdbc:postgresql://fhir-db:5432/hapi
    username: hapi
    password: hapi_2025
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
        show_sql: false
        format_sql: false

hapi:
  fhir:
    fhir_version: R4

    # Permitir IDs personalizados
    allow_external_references: true
    allow_multiple_delete: true

    # Paginación
    default_page_size: 20
    max_page_size: 100

    # CORS
    cors:
      allow_Credentials: true
      allowed_origin:
        - "*"
